Fix to avoid an error we were occasionally getting:
From `bind_rows`:

```
 Error: Can not automatically convert from numeric to character in column "wban_station".
```

This was happening when we tried to bind together some monitors with missing values for the wban or usaf identifier, because that column ended up being character while in other monitors it was numeric.